const supplies = require('..');

const { Coin } = supplies;

const modifiers = [
  'NAFUNDAFO2MHWRR446YHADKR43XQBDJGWFRTMICH',
  'NAFUNDBUKIOSTMD4BNXL7ZFE735QHN7A3FBS6CMY',
  'NAFUNDCJBFWXJWQZITUJOIW4O3E6YHQYQYSISPVA',
  'NAFUNDDWQUHMIKPV2JUH2VNCYEAQX3O7QKHECZUV',
  'NAFUNDEULL67VO7WCJBGBHCLCMD5KEH5EI7G5SGR',
  'NAFUNDHZWSIV4ARXSGGSFONCGFGYTLCB7VOT53SR',
  'NCMARKECQXP3SQZSJPCBKOQWIXRRI7LIS4FTU4VZ',
  'NCONTRLFKPO6YVXO5WUIJ4SWSCSKBJIPV456RSCL',
  'NCOPERAWEWCD4A34NP5UQCCKEX44MW4SL3QYJYS5',
  'NCYZGD-BDTZ42-7NJVPU-JFINWY-PAQBPE-K4OBSS-7MGZ',
  'NDEVPOSK4OMR4PRTLYFHX4W5QTOND7TZDT2DTU4Q',
  'NDEVPRE5ZWVG2PXSM54BGZBFF525G24UKVOGOZNT',
];

const drivers = supplies.selectDriversByBlockchain('Nem');

const driver = new supplies[drivers[0]]();

const coin = new Coin({ modifiers });

driver
  .getSupply(coin)
  .then((supply) => {
    console.log(supply);
  });
